name: link_saver_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.0
  app_links: ^6.4.1
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  html: ^0.15.4
  google_fonts: ^6.2.1
  animations: ^2.0.11
  clerk_flutter: ^0.0.12-beta
  supabase_flutter: ^2.10.3
  firebase_core: any
  flutter_svg: ^2.0.10+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/example_data.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
